server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppooridb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: Syscon311!
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  output:
    ansi:
      enabled: always

#logging:
#  level:
#    '[com.example.kakao]': DEBUG
#    '[org.hibernate.type]': TRACE
#
#file:
#  path: ./images/